"""Seed data for AgroLink.ml — bilingual (PT/EN) sample content.
All products are realistic samples that can be edited/removed via the admin panel.
"""
import uuid


def uid():
    return str(uuid.uuid4())


IMG = "https://images.unsplash.com/photo-{}?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200"


def img(photo_id):
    return IMG.format(photo_id)


CATEGORIES = [
    {
        "id": uid(),
        "slug": "agricultural-inputs",
        "name_pt": "Insumos Agrícolas",
        "name_en": "Agricultural Inputs",
        "desc_pt": "Sementes, fertilizantes, proteção de culturas e outros insumos essenciais.",
        "desc_en": "Seeds, fertilizers, crop protection and other agricultural essentials.",
        "image": img("1574943320219-553eb213f72d"),
        "order": 1,
        "active": True,
    },
    {
        "id": uid(),
        "slug": "animal-feed",
        "name_pt": "Ração e Nutrição Animal",
        "name_en": "Animal Feed & Nutrition",
        "desc_pt": "Soluções de nutrição de qualidade para pecuária e produção animal.",
        "desc_en": "Quality nutrition solutions for livestock and animal production.",
        "image": img("1548550023-2bdb3c5beed7"),
        "order": 2,
        "active": True,
    },
    {
        "id": uid(),
        "slug": "agricultural-products",
        "name_pt": "Produtos Agrícolas",
        "name_en": "Agricultural Products",
        "desc_pt": "Grãos, produtos e commodities agrícolas de produtores confiáveis.",
        "desc_en": "Grains, produce and agricultural commodities from trusted producers.",
        "image": img("1615811361523-6bd03d7748e7"),
        "order": 3,
        "active": True,
    },
    {
        "id": uid(),
        "slug": "equipment-supplies",
        "name_pt": "Equipamentos e Suprimentos",
        "name_en": "Equipment & Supplies",
        "desc_pt": "Equipamentos agrícolas, ferramentas e suprimentos relacionados.",
        "desc_en": "Agricultural equipment, farm tools and related supplies.",
        "image": img("1625246333195-78d9c38ad449"),
        "order": 4,
        "active": True,
    },
]

# category slug lookup helper used below
_cat = {c["slug"]: c["id"] for c in CATEGORIES}


def _p(slug, cat_slug, name_pt, name_en, short_pt, short_en, desc_pt, desc_en,
       apps_pt, apps_en, pack_pt, pack_en, specs, image, featured=False,
       availability="in_stock"):
    return {
        "id": uid(),
        "slug": slug,
        "category_id": _cat[cat_slug],
        "name_pt": name_pt,
        "name_en": name_en,
        "short_desc_pt": short_pt,
        "short_desc_en": short_en,
        "desc_pt": desc_pt,
        "desc_en": desc_en,
        "applications_pt": apps_pt,
        "applications_en": apps_en,
        "packaging_pt": pack_pt,
        "packaging_en": pack_en,
        "specifications": specs,
        "images": [image],
        "featured": featured,
        "availability": availability,
        "status": "active",
    }


PRODUCTS = [
    # ---------------- Agricultural Inputs ----------------
    _p(
        "hybrid-maize-seed", "agricultural-inputs",
        "Semente de Milho Híbrido", "Hybrid Maize Seed",
        "Sementes de milho híbrido de alto rendimento, adaptadas a climas africanos.",
        "High-yield hybrid maize seed adapted to African growing conditions.",
        "Sementes de milho híbrido certificadas, selecionadas para alto rendimento, tolerância à seca e resistência a doenças. Adequadas para produção comercial e familiar em diversas zonas agroecológicas.",
        "Certified hybrid maize seed selected for high yield, drought tolerance and disease resistance. Suitable for commercial and smallholder production across diverse agro-ecological zones.",
        ["Produção comercial de milho", "Agricultura familiar", "Programas de fomento agrícola"],
        ["Commercial maize production", "Smallholder farming", "Agricultural development programs"],
        "Sacos de 10 kg e 25 kg", "10 kg and 25 kg bags",
        [
            {"label_pt": "Germinação", "label_en": "Germination", "value": "≥ 90%"},
            {"label_pt": "Pureza", "label_en": "Purity", "value": "≥ 98%"},
            {"label_pt": "Ciclo", "label_en": "Cycle", "value": "110–130 dias / days"},
        ],
        img("1560493676-04071c5f467b"), featured=True,
    ),
    _p(
        "certified-soybean-seed", "agricultural-inputs",
        "Semente de Soja Certificada", "Certified Soybean Seed",
        "Sementes de soja certificadas para produção de grão e ração.",
        "Certified soybean seed for grain and feed production.",
        "Sementes de soja de variedades comprovadas, com alta taxa de germinação e bom desempenho em diferentes condições de solo. Ideais para produção de grão destinado à alimentação humana e animal.",
        "Proven soybean varieties with high germination rates and strong performance across soil conditions. Ideal for grain production destined for food and animal feed markets.",
        ["Produção de soja em grão", "Rotação de culturas", "Indústria de rações"],
        ["Soybean grain production", "Crop rotation", "Feed industry supply"],
        "Sacos de 25 kg", "25 kg bags",
        [
            {"label_pt": "Germinação", "label_en": "Germination", "value": "≥ 85%"},
            {"label_pt": "Pureza", "label_en": "Purity", "value": "≥ 98%"},
        ],
        img("1592419044706-39796d40f98c"),
    ),
    _p(
        "npk-fertilizer", "agricultural-inputs",
        "Fertilizante NPK 12-24-12", "NPK 12-24-12 Fertilizer",
        "Fertilizante composto para plantio, rico em fósforo.",
        "Compound planting fertilizer with a phosphorus-rich formulation.",
        "Fertilizante granulado NPK 12-24-12 para aplicação no plantio. A formulação rica em fósforo promove o desenvolvimento radicular e o estabelecimento vigoroso das culturas.",
        "Granular NPK 12-24-12 fertilizer for basal application at planting. The phosphorus-rich formulation promotes root development and vigorous crop establishment.",
        ["Milho, soja e feijão", "Hortícolas", "Aplicação de base no plantio"],
        ["Maize, soybean and beans", "Vegetables", "Basal application at planting"],
        "Sacos de 50 kg", "50 kg bags",
        [
            {"label_pt": "N-P-K", "label_en": "N-P-K", "value": "12-24-12"},
            {"label_pt": "Forma", "label_en": "Form", "value": "Granulado / Granular"},
        ],
        img("1592982537447-7440770cbfc9"), featured=True,
    ),
    _p(
        "urea-46", "agricultural-inputs",
        "Ureia 46%", "Urea 46% Fertilizer",
        "Fertilizante nitrogenado de alta concentração para cobertura.",
        "High-concentration nitrogen fertilizer for top dressing.",
        "Ureia granulada com 46% de azoto, indicada para adubação de cobertura em cereais e pastagens. Promove crescimento vegetativo vigoroso e maior produtividade.",
        "Granular urea with 46% nitrogen, recommended for top dressing in cereals and pastures. Promotes vigorous vegetative growth and higher productivity.",
        ["Cobertura em milho e trigo", "Pastagens", "Hortícolas de folha"],
        ["Top dressing in maize and wheat", "Pastures", "Leafy vegetables"],
        "Sacos de 50 kg", "50 kg bags",
        [{"label_pt": "Azoto (N)", "label_en": "Nitrogen (N)", "value": "46%"}],
        img("1530507629858-e4977d30e9e0"),
    ),
    _p(
        "crop-protection-herbicide", "agricultural-inputs",
        "Herbicida de Amplo Espectro", "Broad-Spectrum Herbicide",
        "Proteção de culturas eficaz contra ervas daninhas.",
        "Effective crop protection against grass and broadleaf weeds.",
        "Herbicida sistémico de amplo espectro para controlo de ervas daninhas anuais e perenes. Utilizar sempre de acordo com as instruções do rótulo e com equipamento de proteção adequado.",
        "Systemic broad-spectrum herbicide for control of annual and perennial weeds. Always use according to label instructions with appropriate protective equipment.",
        ["Preparação de terreno", "Controlo de ervas daninhas", "Manutenção de perímetros"],
        ["Land preparation", "Weed control", "Perimeter maintenance"],
        "Embalagens de 1 L, 5 L e 20 L", "1 L, 5 L and 20 L containers",
        [{"label_pt": "Tipo", "label_en": "Type", "value": "Sistémico / Systemic"}],
        img("1625246333195-78d9c38ad449"),
    ),
    _p(
        "vegetable-seed-kit", "agricultural-inputs",
        "Kit de Sementes Hortícolas", "Vegetable Seed Kit",
        "Seleção de sementes hortícolas para produção comercial.",
        "Curated selection of vegetable seeds for market gardening.",
        "Kit com sementes de tomate, cebola, repolho, cenoura e pimento, selecionadas para produtividade e adaptação regional. Ideal para horticultores comerciais e projetos comunitários.",
        "Kit containing tomato, onion, cabbage, carrot and pepper seeds selected for productivity and regional adaptation. Ideal for commercial growers and community projects.",
        ["Horticultura comercial", "Hortas comunitárias", "Projetos de segurança alimentar"],
        ["Market gardening", "Community gardens", "Food security projects"],
        "Kits com 5 variedades", "Kits with 5 varieties",
        [{"label_pt": "Variedades", "label_en": "Varieties", "value": "5"}],
        img("1585155770447-2f66e2a397b5"),
    ),
    # ---------------- Animal Feed & Nutrition ----------------
    _p(
        "broiler-starter-feed", "animal-feed",
        "Ração Inicial para Frangos", "Broiler Starter Feed",
        "Ração completa para frangos de corte de 0 a 21 dias.",
        "Complete feed for broiler chickens from 0 to 21 days.",
        "Ração inicial formulada com proteína de alta qualidade, vitaminas e minerais para um crescimento rápido e saudável de frangos de corte nas primeiras semanas de vida.",
        "Starter feed formulated with high-quality protein, vitamins and minerals to support fast, healthy growth of broiler chickens in the first weeks of life.",
        ["Avicultura de corte", "Produção familiar de frangos", "Integrações avícolas"],
        ["Commercial broiler production", "Family poultry farming", "Poultry integrations"],
        "Sacos de 25 kg e 50 kg", "25 kg and 50 kg bags",
        [
            {"label_pt": "Proteína bruta", "label_en": "Crude protein", "value": "≥ 21%"},
            {"label_pt": "Fase", "label_en": "Phase", "value": "0–21 dias / days"},
        ],
        img("1563281577-a7be47e20db9"), featured=True,
    ),
    _p(
        "layer-feed", "animal-feed",
        "Ração para Poedeiras", "Layer Feed",
        "Nutrição balanceada para máxima produção de ovos.",
        "Balanced nutrition for maximum egg production.",
        "Ração completa para galinhas poedeiras em fase de postura, com níveis adequados de cálcio e aminoácidos para ovos de casca forte e produção consistente.",
        "Complete feed for laying hens in production, with adequate calcium and amino acid levels for strong-shelled eggs and consistent output.",
        ["Produção comercial de ovos", "Avicultura familiar"],
        ["Commercial egg production", "Family poultry farming"],
        "Sacos de 25 kg e 50 kg", "25 kg and 50 kg bags",
        [
            {"label_pt": "Proteína bruta", "label_en": "Crude protein", "value": "≥ 16%"},
            {"label_pt": "Cálcio", "label_en": "Calcium", "value": "3,5–4,0%"},
        ],
        img("1573481078935-b9605167e06b"),
    ),
    _p(
        "cattle-fattening-feed", "animal-feed",
        "Ração para Engorda de Bovinos", "Cattle Fattening Feed",
        "Ração concentrada para acabamento e engorda de bovinos.",
        "Concentrate feed for beef cattle finishing and fattening.",
        "Concentrado energético-proteico para bovinos em fase de engorda, formulado para ganho de peso eficiente em sistemas de confinamento e semi-confinamento.",
        "Energy-protein concentrate for beef cattle in the fattening phase, formulated for efficient weight gain in feedlot and semi-intensive systems.",
        ["Confinamento de bovinos", "Sistemas semi-intensivos", "Acabamento de carcaça"],
        ["Cattle feedlots", "Semi-intensive systems", "Carcass finishing"],
        "Sacos de 50 kg", "50 kg bags",
        [{"label_pt": "Proteína bruta", "label_en": "Crude protein", "value": "≥ 14%"}],
        img("1548550023-2bdb3c5beed7"), featured=True,
    ),
    _p(
        "dairy-feed", "animal-feed",
        "Ração para Vacas Leiteiras", "Dairy Cow Feed",
        "Concentrado para suporte de alta produção de leite.",
        "Concentrate to support high milk production.",
        "Ração concentrada para vacas em lactação, com equilíbrio de energia, proteína e minerais para sustentar a produção de leite e a saúde do animal.",
        "Concentrate feed for lactating cows, balancing energy, protein and minerals to sustain milk production and animal health.",
        ["Produção leiteira", "Cooperativas de leite"],
        ["Dairy production", "Dairy cooperatives"],
        "Sacos de 50 kg", "50 kg bags",
        [{"label_pt": "Proteína bruta", "label_en": "Crude protein", "value": "≥ 18%"}],
        img("1530836369250-ef72a3f5cda8"),
    ),
    _p(
        "pig-grower-feed", "animal-feed",
        "Ração para Suínos em Crescimento", "Pig Grower Feed",
        "Ração completa para suínos em fase de crescimento.",
        "Complete feed for pigs in the growing phase.",
        "Ração balanceada para suínos dos 25 aos 60 kg, formulada para conversão alimentar eficiente e desenvolvimento muscular saudável.",
        "Balanced feed for pigs from 25 to 60 kg, formulated for efficient feed conversion and healthy muscle development.",
        ["Suinocultura comercial", "Produção familiar de suínos"],
        ["Commercial pig farming", "Family pig production"],
        "Sacos de 25 kg e 50 kg", "25 kg and 50 kg bags",
        [{"label_pt": "Proteína bruta", "label_en": "Crude protein", "value": "≥ 16%"}],
        img("1598170845058-32b9d6a5da37"),
    ),
    _p(
        "mineral-block", "animal-feed",
        "Bloco Mineral para Gado", "Mineral Supplement Block",
        "Suplemento mineral em bloco para bovinos e pequenos ruminantes.",
        "Mineral lick block for cattle and small ruminants.",
        "Bloco mineral completo com macro e microminerais essenciais para bovinos, caprinos e ovinos em pastagem. Melhora a fertilidade, imunidade e desempenho geral do rebanho.",
        "Complete mineral block with essential macro and trace minerals for grazing cattle, goats and sheep. Improves herd fertility, immunity and overall performance.",
        ["Gado em pastagem", "Caprinos e ovinos", "Suplementação na época seca"],
        ["Grazing cattle", "Goats and sheep", "Dry-season supplementation"],
        "Blocos de 5 kg e 20 kg", "5 kg and 20 kg blocks",
        [{"label_pt": "Tipo", "label_en": "Type", "value": "Bloco de lamber / Lick block"}],
        img("1500382017468-9049fed747ef"),
    ),
    # ---------------- Agricultural Products ----------------
    _p(
        "yellow-maize-grain", "agricultural-products",
        "Milho Amarelo em Grão", "Yellow Maize Grain",
        "Milho amarelo de qualidade para ração e indústria.",
        "Quality yellow maize for feed and industrial use.",
        "Milho amarelo em grão, limpo e seco, adequado para a indústria de rações e processamento alimentar. Disponível em volumes comerciais com origem rastreável.",
        "Clean, dried yellow maize grain suitable for the feed industry and food processing. Available in commercial volumes with traceable origin.",
        ["Indústria de rações", "Moagem", "Comércio de grãos"],
        ["Feed industry", "Milling", "Grain trading"],
        "Sacos de 50 kg ou a granel", "50 kg bags or bulk",
        [
            {"label_pt": "Humidade", "label_en": "Moisture", "value": "≤ 13,5%"},
            {"label_pt": "Impurezas", "label_en": "Impurities", "value": "≤ 2%"},
        ],
        img("1551754655-cd27e38d2076"), featured=True,
    ),
    _p(
        "white-maize-grain", "agricultural-products",
        "Milho Branco em Grão", "White Maize Grain",
        "Milho branco para consumo humano e moagem.",
        "White maize for human consumption and milling.",
        "Milho branco em grão destinado ao consumo humano e à produção de fuba. Selecionado por qualidade, cor e baixo teor de humidade.",
        "White maize grain destined for human consumption and maize meal production. Selected for quality, colour and low moisture content.",
        ["Moagem de fuba", "Consumo humano", "Programas alimentares"],
        ["Maize meal milling", "Human consumption", "Food programs"],
        "Sacos de 25 kg e 50 kg", "25 kg and 50 kg bags",
        [{"label_pt": "Humidade", "label_en": "Moisture", "value": "≤ 13%"}],
        img("1618512496248-a07fe83aa8cb"),
    ),
    _p(
        "soybean-grain", "agricultural-products",
        "Soja em Grão", "Soybean Grain",
        "Soja em grão para esmagamento e indústria de rações.",
        "Soybean grain for crushing and the feed industry.",
        "Soja em grão de produtores selecionados, adequada para esmagamento, produção de óleo e farelo, e formulação de rações de alta proteína.",
        "Soybean grain from selected producers, suitable for crushing, oil and meal production, and high-protein feed formulation.",
        ["Esmagamento e óleo", "Farelo para rações", "Exportação"],
        ["Crushing and oil", "Meal for feed", "Export markets"],
        "Sacos de 50 kg ou a granel", "50 kg bags or bulk",
        [{"label_pt": "Proteína", "label_en": "Protein", "value": "≥ 34%"}],
        img("1589923188900-85dae523342b"),
    ),
    _p(
        "dried-beans", "agricultural-products",
        "Feijão Seco", "Dried Beans",
        "Feijão seco selecionado de produtores regionais.",
        "Selected dried beans from regional producers.",
        "Feijão seco de variedades regionais, limpo e calibrado, para mercados grossistas, retalho e programas institucionais.",
        "Dried beans of regional varieties, cleaned and graded, for wholesale, retail and institutional programs.",
        ["Comércio grossista", "Retalho alimentar", "Programas institucionais"],
        ["Wholesale trade", "Food retail", "Institutional programs"],
        "Sacos de 25 kg e 50 kg", "25 kg and 50 kg bags",
        [{"label_pt": "Calibragem", "label_en": "Grading", "value": "Limpo e calibrado / Cleaned & graded"}],
        img("1607305387299-a3d9611cd469"),
    ),
    _p(
        "sunflower-seed-grain", "agricultural-products",
        "Girassol em Grão", "Sunflower Seed",
        "Girassol para extração de óleo e ração animal.",
        "Sunflower seed for oil extraction and animal feed.",
        "Girassol em grão para a indústria de óleo alimentar e para formulação de rações. Disponível conforme a época de colheita e volumes contratados.",
        "Sunflower seed for the edible oil industry and feed formulation. Available according to harvest season and contracted volumes.",
        ["Extração de óleo", "Indústria de rações"],
        ["Oil extraction", "Feed industry"],
        "Sacos de 50 kg ou a granel", "50 kg bags or bulk",
        [{"label_pt": "Teor de óleo", "label_en": "Oil content", "value": "≥ 38%"}],
        img("1470549638415-0a0755be0619"), availability="on_request",
    ),
    # ---------------- Equipment & Supplies ----------------
    _p(
        "knapsack-sprayer", "equipment-supplies",
        "Pulverizador Costal 20 L", "Knapsack Sprayer 20 L",
        "Pulverizador manual robusto para proteção de culturas.",
        "Durable manual sprayer for crop protection application.",
        "Pulverizador costal de 20 litros com bomba de pressão manual, lança ajustável e correias confortáveis. Ideal para aplicação de herbicidas, inseticidas e fertilizantes foliares.",
        "20-litre knapsack sprayer with manual pressure pump, adjustable lance and comfortable straps. Ideal for applying herbicides, insecticides and foliar fertilizers.",
        ["Aplicação de defensivos", "Fertilização foliar", "Higienização rural"],
        ["Crop protection application", "Foliar feeding", "Rural sanitation"],
        "Unidade", "Per unit",
        [
            {"label_pt": "Capacidade", "label_en": "Capacity", "value": "20 L"},
            {"label_pt": "Material", "label_en": "Material", "value": "HDPE"},
        ],
        img("1416879595882-3373a0480b5b"),
    ),
    _p(
        "drip-irrigation-kit", "equipment-supplies",
        "Kit de Irrigação Gota a Gota", "Drip Irrigation Kit",
        "Sistema de irrigação eficiente para hortas e pomares.",
        "Water-efficient irrigation system for gardens and orchards.",
        "Kit completo de irrigação gota a gota para até 500 m², incluindo mangueiras, gotejadores, filtro e conectores. Reduz o consumo de água e aumenta a produtividade.",
        "Complete drip irrigation kit for up to 500 m², including lines, drippers, filter and connectors. Reduces water use and increases productivity.",
        ["Horticultura", "Pomares", "Estufas"],
        ["Vegetable production", "Orchards", "Greenhouses"],
        "Kit completo em caixa", "Complete boxed kit",
        [{"label_pt": "Área coberta", "label_en": "Coverage", "value": "até / up to 500 m²"}],
        img("1444858291040-58f756a3bdd6"),
    ),
    _p(
        "poultry-equipment", "equipment-supplies",
        "Bebedouros e Comedouros Avícolas", "Poultry Drinkers & Feeders",
        "Equipamento essencial para aviários de todas as dimensões.",
        "Essential equipment for poultry houses of all sizes.",
        "Linha de bebedouros automáticos e comedouros tubulares para aviários, em plástico resistente e de fácil limpeza. Disponíveis em vários tamanhos.",
        "Range of automatic drinkers and tube feeders for poultry houses, made of durable, easy-to-clean plastic. Available in multiple sizes.",
        ["Avicultura de corte", "Poedeiras", "Criação familiar"],
        ["Broiler production", "Layers", "Family poultry"],
        "Unidade ou caixas de 10", "Per unit or boxes of 10",
        [{"label_pt": "Material", "label_en": "Material", "value": "Plástico / Plastic"}],
        img("1563281577-a7be47e20db9"),
    ),
    _p(
        "hermetic-grain-bags", "equipment-supplies",
        "Sacos Herméticos para Grãos", "Hermetic Grain Storage Bags",
        "Armazenamento seguro de grãos sem químicos.",
        "Safe, chemical-free grain storage solution.",
        "Sacos herméticos de armazenamento que protegem os grãos contra insetos e humidade sem uso de químicos, preservando a qualidade por longos períodos.",
        "Hermetic storage bags that protect grain against insects and moisture without chemicals, preserving quality over long periods.",
        ["Armazenamento pós-colheita", "Bancos de sementes", "Comércio de grãos"],
        ["Post-harvest storage", "Seed banks", "Grain trading"],
        "Fardos de 50 e 100 sacos", "Bundles of 50 and 100 bags",
        [{"label_pt": "Capacidade", "label_en": "Capacity", "value": "50 kg / 100 kg"}],
        img("1524594152303-9fd13543fe6e"),
    ),
]


TEAM = [
    {
        "id": uid(),
        "name": "Membro da Equipa 1",
        "role_pt": "Diretor Geral",
        "role_en": "Managing Director",
        "bio_pt": "Adicione aqui a biografia deste membro da equipa através do painel de administração.",
        "bio_en": "Add this team member's biography here via the admin panel.",
        "photo": "",
        "order": 1,
        "active": True,
    },
    {
        "id": uid(),
        "name": "Membro da Equipa 2",
        "role_pt": "Diretor Comercial",
        "role_en": "Commercial Director",
        "bio_pt": "Adicione aqui a biografia deste membro da equipa através do painel de administração.",
        "bio_en": "Add this team member's biography here via the admin panel.",
        "photo": "",
        "order": 2,
        "active": True,
    },
    {
        "id": uid(),
        "name": "Membro da Equipa 3",
        "role_pt": "Gestor de Operações",
        "role_en": "Operations Manager",
        "bio_pt": "Adicione aqui a biografia deste membro da equipa através do painel de administração.",
        "bio_en": "Add this team member's biography here via the admin panel.",
        "photo": "",
        "order": 3,
        "active": True,
    },
]


SETTINGS = {
    "id": "site-settings",
    "email": "agrolink.ml@gmail.com",
    "phone_angola": "+244 924 546 980",
    "phone_namibia": "+264 85 379 4593",
    "whatsapp_angola": "+244924546980",
    "whatsapp_namibia": "+26485379 4593".replace(" ", ""),
    "address_angola": "Angola",
    "address_namibia": "Namíbia / Namibia",
    "facebook": "",
    "instagram": "",
    "linkedin": "",
}
